import PptxGenJS from 'pptxgenjs';
import type { SlideDeckSpec, SlideSpec } from './types';

const BG = '0B1020';
const ACCENT1 = '7C3AED';
const ACCENT2 = '06B6D4';
const TEXT = 'E2E8F0';
const MUTED = '94A3B8';

function addCoverSlide(pptx: PptxGenJS, s: Extract<SlideSpec, { type: 'cover' }>) {
  const slide = pptx.addSlide();
  slide.background = { color: BG };
  slide.addText(s.projectName, {
    x: 0.5,
    y: 1.2,
    w: 9,
    h: 1.2,
    fontSize: 36,
    bold: true,
    color: TEXT,
    fontFace: 'Arial',
  });
  slide.addText(s.tagline, {
    x: 0.5,
    y: 2.5,
    w: 9,
    h: 0.8,
    fontSize: 18,
    color: MUTED,
    fontFace: 'Arial',
  });
  slide.addText(s.repoUrl, {
    x: 0.5,
    y: 4.2,
    w: 9,
    h: 0.5,
    fontSize: 12,
    color: ACCENT2,
    fontFace: 'Arial',
  });
  slide.addText(`생성일: ${s.generatedAt}`, {
    x: 0.5,
    y: 4.8,
    w: 9,
    h: 0.4,
    fontSize: 11,
    color: MUTED,
    fontFace: 'Arial',
  });
}

function addBulletsSlide(pptx: PptxGenJS, s: Extract<SlideSpec, { type: 'bullets' }>) {
  const slide = pptx.addSlide();
  slide.background = { color: BG };
  slide.addText(s.title, {
    x: 0.5,
    y: 0.45,
    w: 9,
    h: 0.7,
    fontSize: 28,
    bold: true,
    color: TEXT,
    fontFace: 'Arial',
  });
  const bulletBlocks = s.bullets.map((b) => ({
    text: b,
    options: { bullet: true, fontSize: 16, color: TEXT, fontFace: 'Arial' },
  }));
  slide.addText(bulletBlocks as Parameters<typeof slide.addText>[0], {
    x: 0.6,
    y: 1.3,
    w: 8.8,
    h: 4.5,
    valign: 'top',
  });
  slide.addShape(pptx.ShapeType.rect, {
    x: 0.35,
    y: 0.35,
    w: 0.08,
    h: 0.9,
    fill: { color: ACCENT1 },
    line: { color: ACCENT1, width: 0 },
  });
}

function addCardsSlide(pptx: PptxGenJS, s: Extract<SlideSpec, { type: 'cards' }>) {
  const slide = pptx.addSlide();
  slide.background = { color: BG };
  slide.addText(s.title, {
    x: 0.5,
    y: 0.4,
    w: 9,
    h: 0.7,
    fontSize: 28,
    bold: true,
    color: TEXT,
    fontFace: 'Arial',
  });
  const cols = Math.min(s.cards.length, 3);
  const cardW = 9 / cols - 0.25;
  let x = 0.45;
  const y = 1.35;
  for (let i = 0; i < cols; i++) {
    const c = s.cards[i];
    if (!c) break;
    slide.addShape(pptx.ShapeType.roundRect, {
      x,
      y,
      w: cardW,
      h: 3.6,
      fill: { color: '111827' },
      line: { color: ACCENT1, width: 1 },
    });
    slide.addText(c.title, {
      x: x + 0.15,
      y: y + 0.2,
      w: cardW - 0.3,
      h: 0.55,
      fontSize: 16,
      bold: true,
      color: ACCENT2,
      fontFace: 'Arial',
    });
    slide.addText(c.body, {
      x: x + 0.15,
      y: y + 0.85,
      w: cardW - 0.3,
      h: 2.6,
      fontSize: 13,
      color: TEXT,
      fontFace: 'Arial',
      valign: 'top',
    });
    x += cardW + 0.2;
  }
}

function addFlowSlide(pptx: PptxGenJS, s: Extract<SlideSpec, { type: 'flow' }>) {
  const slide = pptx.addSlide();
  slide.background = { color: BG };
  slide.addText(s.title, {
    x: 0.5,
    y: 0.4,
    w: 9,
    h: 0.7,
    fontSize: 28,
    bold: true,
    color: TEXT,
    fontFace: 'Arial',
  });
  const joined = s.steps.join('  →  ');
  slide.addText(joined, {
    x: 0.5,
    y: 1.8,
    w: 9,
    h: 2.2,
    fontSize: 18,
    color: TEXT,
    fontFace: 'Arial',
    align: 'center',
    valign: 'middle',
  });
}

function addClosingSlide(pptx: PptxGenJS, s: Extract<SlideSpec, { type: 'closing' }>) {
  const slide = pptx.addSlide();
  slide.background = { color: BG };
  slide.addText('Thank You', {
    x: 0.5,
    y: 1.8,
    w: 9,
    h: 1,
    fontSize: 40,
    bold: true,
    color: TEXT,
    align: 'center',
    fontFace: 'Arial',
  });
  slide.addText(s.repoUrl, {
    x: 0.5,
    y: 3,
    w: 9,
    h: 0.5,
    fontSize: 14,
    color: ACCENT2,
    align: 'center',
    fontFace: 'Arial',
  });
  slide.addText('Generated by AI', {
    x: 0.5,
    y: 3.7,
    w: 9,
    h: 0.4,
    fontSize: 12,
    color: MUTED,
    align: 'center',
    fontFace: 'Arial',
  });
}

export async function buildPptxBuffer(spec: SlideDeckSpec): Promise<Buffer> {
  const pptx = new PptxGenJS();
  pptx.layout = 'LAYOUT_16x9';
  pptx.author = 'Git Repository Presentation Generator';
  pptx.subject = 'Auto-generated deck';

  for (const s of spec.slides) {
    switch (s.type) {
      case 'cover':
        addCoverSlide(pptx, s);
        break;
      case 'bullets':
        addBulletsSlide(pptx, s);
        break;
      case 'cards':
        addCardsSlide(pptx, s);
        break;
      case 'flow':
        addFlowSlide(pptx, s);
        break;
      case 'closing':
        addClosingSlide(pptx, s);
        break;
      default:
        break;
    }
  }

  const data = await pptx.write({ outputType: 'nodebuffer' });
  return data as Buffer;
}
